name: test toy project
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
      - name: install python packages
        run: |
          pip install -r examples/requirements.txt
          pip install ./examples
      - name: run tests
        run: pytest examples
